### ISSUE TITLE
Install.py: Could not find firefox release header '138.0'.

### ISSUE THREAD

**Issue by andrea-citterio** [yokoffing/Betterfox#402]
I have version 136.0.4 but i get this error message: 
`Could not find firefox release header '138.0'. Please post this error message on https://github.com/yokoffing/Betterfox/issues`
is it normal?

**Comment by yokoffing** [comment]
Resolved [here](https://github.com/yokoffing/Betterfox/commit/1a6be093dca7a7d95a54b72ac2215b241e7975a9), but awaiting pull request from @sykoram.

**Comment by sykoram** [comment]
Sorry for the delay, the PR is ready now (#405)!

**Comment by sykoram** [comment]
Even after updating install.py, the error is still there.

I've inspected the script and found out that it expects "Firefox Releases" section in the release description, but there is none for the 138.0. Is this intentional?

**Comment by yokoffing** [comment]
@sykoram That's... interesting. But not great that it relies on that.

I usually have that section in the release notes, but didn't include it in the last release. I can add it.

**Comment by yokoffing** [comment]
I've now added a "Firefox Releases" section like we normally have in the release notes.

**Comment by Denperidge** [comment]
> [@sykoram](https://github.com/sykoram) That's... interesting. But not great that it relies on that.

Is there a different source to get compatible release info from for betterfox?
